id: P29F6C532
initial_creation_type: input
source_metadata:
  title: Rongtön Sheja Künrig Series
  language: pt
  description: Rongtön Sheja Kunrig (rong ston shes bya kun rig), also known as Shakya
    Gyaltsen, (shakya rgyal mtshan, 1367-1449) was one of the greatest scholars of
    the Sakya school, renowned especially for his mastery of the prajñāpāramitā teachings.
    He founded Nalendra Monastery in 1436.
  volume:
    984194946ccb4c8787baa1789f493751:
      title: 'The Joyous Entrance to the Path to Liberation: How to Practise the Six
        Transcendent Perfections'
      parent: Advice
    d4076654598f457da1e612eff9d4eb78:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    fdd4d770b6f44613bbc3d9ae98146793:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: Middle Way
    91b1757d31254780b305b9c28212a7e9:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Praise
    0ddd7df67a384b2db4f5fd52a12c2b9e:
      title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of
        the Lineage of Gurus for the Noble Abhidharma'
      parent: Praise
    d3dbd2ed5e624a02a905ff80f3582d87:
      title: Elucidating the Essence of the Instructions for Entering the Three Gateways
        to Liberation
      parent: Three Gateways to Liberation
    7d7b893805cc4c589e58cd53b3538b16:
      title: 'The Excellent Path of the Great Vehicle: How to Meditate on the Three
        Gateways to Liberation According to the Mahāyāna'
      parent: Three Gateways to Liberation
created_at: '2022-03-01T01:24:12.899693'
last_modified_at: '2022-03-01T01:24:12.899695'
